services:
  demo_racecondition:
    image: ${DOCKER_REGISTRY-}demoracecondition
    build:
      context: .
      dockerfile: demo_RaceCondition/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=demo_bypass;User=sa;Password=s7venking2001.
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "s7venking2001."
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
